volumes: 
  postgres_data: 
    driver: local

services:

# POSTGRES KEYCLOAK
  postgres: 
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment: 
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  
  # KEYCLOAK
  keycloak: 
    image: quay.io/keycloak/keycloak:latest
    environment: 
      DB_VENDOR: POSTGRES 
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public 
      DB_PASSWORD: password 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports: 
      - 9101:8080
    depends_on: 
      - postgres